SELECT
FBSS.SEG_LOCAL_UPLIFT_DT as Upl_Dt
,FBSS.SEG_UPLIFT_STN_CD as Upl_Stn
,FBSS.SEG_DISCHARGE_STN_CD  as Dis_Stn
,FBSS.SEG_OPERATING_FLT_NO as Flt_No
,FBSS.WEEKS_BEFORE_DEPARTURE_NO  as WTD
,RAC.Day_of_Week_NO as Day_Of_Week
,RAC.calendar_Month_no as Calendar_Month
,SSFC.Capacity
,RSP.GC_KM_DIS*SSFC.Capacity as ASK
,SUBSTR(CAST(SCHED_DEP_TM AS VARCHAR(20)),12,2) AS HOUR_OF_DEP
,T.ROUTE_TYP_CD as Route_Type
,SUM (ZEROIFNULL (FBSS.PAX_QTY))  AS  PSJS
,((SUM(ZEROIFNULL(FBSS.REV_GROSS_VLU)-ZEROIFNULL(FBSS.REV_SPC_VLU) + ZEROIFNULL(FBSS.YQ_TAX_VLU) + ZEROIFNULL(FBSS.RED_REV_VLU) + ZEROIFNULL(FBSS.RED_UPG_REV_VLU))/(ASK/1000))) as Rev_Over_ASK
,SUM(cast(ZEROIFNULL (FBSS.PAX_QTY) as float)/SSFC.Capacity) AS  Seat_Factor

FROM  FORWARD_BOOKINGS_SNAPSHOT_SUMM  FBSS

JOIN REF_ACCOUNTING_CALENDAR RAC
ON FBSS.SEG_LOCAL_UPLIFT_DT = RAC.Calendar_Dt

LEFT JOIN REF_STATION_PAIR RSP
ON RSP.DEP_STN_CD = FBSS.SEG_UPLIFT_STN_CD
AND RSP.ARR_STN_CD = FBSS.SEG_DISCHARGE_STN_CD

LEFT JOIN 
(select             
			  SCHED_DEP_DT
              ,OPERATING_FLT_NO
              ,DEP_STN_CD
              ,ARR_STN_CD
				,SUM(CAPACITY_QTY) as CAPACITY

from SCHEDULE_SALES_FLT_CAPACITY

WHERE
    OPERATING_AIRLINE_CD = 'BA'
             AND CURRENT_REC_IND = 'Y'
			 and current_date between effective_DT and expiry_dt
			 AND SCHED_DEP_DT between '2019-06-03' and  '2019-07-03'
			 
Group by 1, 2, 3, 4
) SSFC
ON SSFC.OPERATING_FLT_NO = FBSS.SEG_OPERATING_FLT_NO
AND SSFC.DEP_STN_CD = FBSS.SEG_UPLIFT_STN_CD
AND SSFC.ARR_STN_CD = FBSS.SEG_DISCHARGE_STN_CD
AND SSFC.SCHED_DEP_DT = FBSS.SEG_LOCAL_UPLIFT_DT

LEFT JOIN SCHEDULE_SALES_FLT_LEG SSFL
ON SSFL.SCHED_DEP_DT = FBSS.SEG_LOCAL_UPLIFT_DT
AND SSFL.OPERATING_FLT_NO = FBSS.SEG_OPERATING_FLT_NO
and SSFL.CURRENT_REC_IND = 'Y'
and current_date between SSFL.effective_DT and SSFL.expiry_dt

LEFT JOIN 
(SELECT 
ROUTE_TYP_CD,
ROUTE_TYP_NM,
 DEP_STN_CD,
 ARR_STN_CD

FROM LDB_SBOX_OR.TYPE_ROUTE TR

 LEFT JOIN
(select 
DEP_STN_CD
,ARR_STN_CD
,(STN_1_CD||'-'||STN_2_CD) as ROUTE
from REF_STATION_PAIR) R
ON R.ROUTE=TR.ROUTE_TXT) T
ON T.DEP_STN_CD = FBSS.SEG_UPLIFT_STN_CD
AND T.ARR_STN_CD = FBSS.SEG_DISCHARGE_STN_CD

WHERE  FBSS.SEG_OPERATING_AIRLINE_CD  =  'BA' /*BA only*/
AND  FBSS.BKG_CURR_INVENTORY_STS_CD    ='K' /* CONFIRMED PAX ONLY */
AND  FBSS.PAX_TKTD_REV_PAX_CD ='Y'  /* REV PAX ONLY */
AND  FBSS.BUSINESS_UNIT_CD  IN ('BAW')     /* BA MAINLINE*/
and FBSS.SEG_LOCAL_UPLIFT_DT between '2019-06-03' and '2019-07-03'
and  FBSS.SNAPSHOT_DT between FBSS.SEG_LOCAL_UPLIFT_DT-365 and  FBSS.SEG_LOCAL_UPLIFT_DT+7
AND (FBSS.SEG_UPLIFT_STN_CD in ('LHR') OR FBSS.SEG_DISCHARGE_STN_CD in ('LHR'))
AND FBSS.SEG_UPLIFT_STN_CD not in  ('MAD', 'SYD', 'GCM') AND FBSS.SEG_DISCHARGE_STN_CD not in  ('MAD', 'SYD', 'GCM')
AND SSFL.OPERATING_AIRLINE_CD = 'BA'
AND SSFL.CURRENT_REC_IND = 'Y' 
AND SSFC.Capacity is not null

GROUP  BY  1,2,3,4,5, 6, 7, 8, 9,10,11
ORDER BY Flt_No, Upl_Dt, WTD